easy_admin:
  design:
    assets:
      css:
        - '/assets/bs-tags/bootstrap-tagsinput.css'
        - '/assets/smart-wizard/css/smart_wizard.css'
        - '/assets/smart-wizard/css/smart_wizard_theme_arrows.css'
        - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css
        - assets/css/select2.css
        - assets/css/ct.css
      js:
        - assets/js/popper.js
        - assets/js/bootstrap.js
        - assets/js/app-style-switcher.js
        - assets/js/perfect-scrollbar.jquery.min.js
        - assets/js/feather.js
        - assets/js/sidebar.js
        - assets/js/custom.js
        - '/assets/bs-tags/bootstrap-tagsinput.js'
        - '/assets/smart-wizard/js/jquery.smartWizard.js'
    form_theme: 'form/fields.html.twig'
    menu:
      - {label: "Entities"}
      - label: "Posts"
        children:
          - {entity: Post, label: "Posts list", icon: "th-list"}
          - {entity: Post, label: "Add post", icon: "plus", params: {action: 'new'}, permission: 'ROLE_ADMIN'}
      - label: "Category"
        children:
          - {entity: Category, label: "List all categories", icon: "th-list"}
          - {entity: Category, label: "Add category", icon: "plus"}
      - Tag
      - {label: "Settings"}
      - {entity: User, icon: "user", permission: 'ROLE_ADMIN'}
      - Checkout
  site_name: 'OverSeas <b>Media</b>'
  user:
    display_name: true
    display_avatar: true
    name_property_path: 'fullName'
  entities:
    Post:
      controller: App\Controller\PostController
      class: App\Entity\Post
      label: "Post"
      help: Shit videos
      form:
        fields:
            - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-12'}
            - title
            - {property: 'content'}
            - createdAt
            - published
            - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-6'}
            - category
            - { property: 'tags', type: 'App\Form\TagType', type_options: {attr: {data-role: 'tagsinput'}}}
            - {type: 'group', icon: 'clip', label: 'Attachments', css_class: 'col-lg-6'}
            - { property: 'thumbnailFile', type: 'vich_image' }
            - { property: 'attachments', type: 'collection', type_options: {entry_type: 'App\Form\AttachmentType', by_reference: false} }
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Some posts from the other world"
        fields: ['title', 'content', 'createdAt', {property: 'user.email', label: 'Author', permission: 'ROLE_ADMIN'}, {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}]
        filters: ['published']
      show:
        fields:
          - title
          - {property: 'content', type: 'raw'}
          - createdAt
          - published
          - {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}
          - {property: 'attachments', template: 'images.html.twig' }
          - tags
      edit:
        help: "Hello there"
      new:
        item_permission: 'ROLE_ADMIN'

    Category:
      class: App\Entity\Category
    Tag:
      class: App\Entity\Tag
      form:
        fields:
          - name
          - slug
    User:
      class: App\Entity\User
      list:
        item_permission: 'ROLE_ADMIN'

    Checkout:
      class: App\Entity\Checkout
      templates:
        new: 'admin/checkout/new.html.twig'
      new:
        actions:
          - '-list'